In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
# reference year: 2022
# https://ec.europa.eu/eurostat/databrowser/view/nama_10_a10__custom_20687844/default/table?lang=en
# https://ec.europa.eu/eurostat/databrowser/view/nama_10_a10_e/default/table?lang=en

av_agri = pd.read_excel("nama_av_agri.xlsx", sheet_name = "Sheet 1")
av_tot = pd.read_excel("nama_tot_av.xlsx" , sheet_name = "Sheet 1")
tot_emp = pd.read_excel("nama_tot_emp.xlsx" , sheet_name = "Sheet 1")
emp = pd.read_excel("nama_emp.xlsx" , sheet_name = "Sheet 1")
agri_tot_emp = pd.read_excel("agri_tot_emp.xlsx" , sheet_name = "Sheet 1")
agri_emp = pd.read_excel("agri_emp.xlsx" , sheet_name = "Sheet 1")

nama_av_files = [av_agri, av_tot, tot_emp, emp, agri_tot_emp, agri_emp]

countryNames=['Austria', 'Belgium', 'Bulgaria', 'Croatia', 'Cyprus', 'Czechia', 
              'Denmark', 'Estonia', 'Finland', 'France', 'Germany', 'Greece', 
              'Hungary', 'Ireland', 'Italy', 'Latvia', 'Lithuania', 'Luxembourg', 
              'Malta', 'Netherlands', 'Poland', 'Portugal', 'Romania', 'Slovakia', 
              'Slovenia', 'Spain', 'Sweden', 'totEU27']


for i in range(len(nama_av_files)):
    nama_av_files[i] = nama_av_files[i][10:38]
    nama_av_files[i] = nama_av_files[i].drop("Unnamed: 2", axis=1)
    nama_av_files[i].columns = ['country', 'AV']
    nama_av_files[i].iloc[0,0] = 'totEU27'
    nama_av_files[i]["country"] = pd.Categorical(nama_av_files[i]["country"], categories=countryNames, ordered=True)
    nama_av_files[i] = nama_av_files[i].sort_values("country")
    nama_av_files[i] = nama_av_files[i].reset_index(drop=True)

In [3]:
nama_av = pd.DataFrame()
nama_av['country'] = nama_av_files[0]['country']
nama_av['agri_AV'] = nama_av_files[0]['AV']
nama_av['all_nace_AV'] =  nama_av_files[1]['AV']

nama_av['nace_noagri_AV'] = nama_av['all_nace_AV'] - nama_av['agri_AV'] 

nama_av['tot_emp'] = nama_av_files[2]['AV']
nama_av['emp'] = nama_av_files[3]['AV']
nama_av['agri_tot_emp'] = nama_av_files[4]['AV']
nama_av['agri_emp'] = nama_av_files[5]['AV']

nama_av['nace_noagri_tot_emp'] = nama_av['tot_emp'] - nama_av['agri_tot_emp'] 
nama_av['nace_noagri_emp'] = nama_av['emp'] - nama_av['agri_emp'] 

nama_av['tot_prod'] = nama_av['all_nace_AV'] / nama_av['tot_emp'] 
nama_av['prod'] = nama_av['all_nace_AV'] / nama_av['emp'] 

nama_av['agri_tot_prod'] = nama_av['agri_AV']/ nama_av['agri_tot_emp'] 
nama_av['agri_prod'] = nama_av['agri_AV']/ nama_av['agri_emp']

nama_av['noagri_tot_prod'] = nama_av['nace_noagri_AV'] / nama_av['nace_noagri_tot_emp']
nama_av['noagri_prod'] = nama_av['nace_noagri_AV'] / nama_av['nace_noagri_emp']


# NB: tot_prod accounts also for self-employers, prod accounts only for the employees

nama_av

,country,agri_AV,all_nace_AV,nace_noagri_AV,tot_emp,emp,agri_tot_emp,agri_emp,nace_noagri_tot_emp,nace_noagri_emp,tot_prod,prod,agri_tot_prod,agri_prod,noagri_tot_prod,noagri_prod
0,Austria,6050.9,402767.1,396716.2,4690.42,4123.93,149.98,30.41,4540.44,4093.52,85.870157,97.665843,40.344713,198.97731,87.373955,96.913219
1,Belgium,3768.8,505988,502219.2,5052.8,4175.7,59.5,28,4993.3,4147.7,100.14012,121.174414,63.341176,134.6,100.578615,121.083781
2,Bulgaria,3194.7,76531.2,73336.5,3444.4,2609.12,521.84,98.63,2922.56,2510.49,22.219022,29.332189,6.121991,32.390753,25.09324,29.212026
3,Croatia,2294.1,56301.4,54007.3,1642.52,1414.41,94.58,36.83,1547.94,1377.58,34.277452,39.805573,24.255657,62.288895,34.889789,39.204475
4,Cyprus,351.6,26300.6,25949.0,482.51,429.09,15.99,7.19,466.52,421.9,54.507886,61.293901,21.988743,48.901252,55.622481,61.505096
5,Czechia,5958.6,261260.4,255301.8,5333.08,4577.74,154.17,106.7,5178.91,4471.04,48.988652,57.071918,38.649543,55.844424,49.296435,57.101211
6,Denmark,3814.4,335283.5,331469.1,3161.16,2981.21,65.75,40.95,3095.41,2940.26,106.063439,112.465576,58.013688,93.147741,107.08407,112.734622
7,Estonia,888.1,32031.2,31143.1,668.08,597.95,17.2,11.42,650.88,586.53,47.945156,53.568359,51.633721,77.767075,47.847683,53.097199
8,Finland,5965,231139,225174,2742.8,2450.5,87,31.4,2655.8,2419.1,84.271183,94.323199,68.563218,189.968153,84.785752,93.081725
9,France,45653.3,2368609.4,2322956.1,30064,26808,713,363,29351,26445,78.785571,88.354573,64.029874,125.766667,79.144019,87.841032
10,Germany,39680,3591874,3552194,45629,41767,577,360,45052,41407,78.719104,85.997893,68.769497,110.222222,78.846533,85.787282
11,Greece,7835.1,182631.3,174796.2,5037.39,3687.3,508.29,116.31,4529.1,3570.99,36.255144,49.529819,15.414626,67.363941,38.594025,48.948947
12,Hungary,5297.6,143250.4,137952.8,4755.96,4348.92,160.94,113.84,4595.02,4235.08,30.120186,32.939304,32.916615,46.535488,30.022241,32.573836
13,Ireland,6107.1,496977.9,490870.8,2594.53,2230.13,104.16,24.46,2490.37,2205.67,191.548334,222.847054,58.631912,249.677024,197.107578,222.54952
14,Italy,37771,1793606.6,1755835.6,25550.4,19594.6,940.2,444.8,24610.2,19149.8,70.198768,91.53576,40.173367,84.916817,71.345848,91.689501
15,Latvia,1845.6,31521.4,29675.8,906.07,782.27,70,36.66,836.07,745.61,34.789144,40.294783,26.365714,50.343699,35.494396,39.8007
16,Lithuania,2649.3,60696.1,58046.8,1455.47,1280.15,78.28,38.3,1377.19,1241.85,41.702062,47.413272,33.843894,69.172324,42.148723,46.742199
17,Luxembourg,185.8,69430.3,69244.5,501.25,472.32,4.46,1.67,496.79,470.65,138.514314,146.998433,41.659193,111.257485,139.383844,147.125252
18,Malta,149.9,16672.8,16522.9,290.19,248.76,3.79,1.34,286.4,247.42,57.454771,67.023637,39.551451,111.865672,57.69169,66.780778
19,Netherlands,16318,888174,871856,10000,8340,197,104,9803,8236,88.8174,106.495683,82.832487,156.903846,88.937672,105.859155
20,Poland,18568.1,590308.8,571740.7,17512,14022.1,1486.1,126.2,16025.9,13895.9,33.708817,42.098459,12.494516,147.13233,35.676043,41.144561
21,Portugal,4648.4,211027.9,206379.5,5137.9,4331.78,300.69,101.05,4837.21,4230.73,41.072792,48.716209,15.459111,46.00099,42.664987,48.781061
22,Romania,10720.2,257784.6,247064.4,8599.5,6688.7,1792.1,233.1,6807.4,6455.6,29.976696,38.540314,5.981921,45.989704,36.293504,38.27133
23,Slovakia,2122.7,97975.3,95852.6,2427.3,2085.37,69.67,53.68,2357.63,2031.69,40.363902,46.982214,30.46792,39.543592,40.656337,47.178753
24,Slovenia,924.2,49934.2,49010.0,1082.59,872.89,69.19,4.4,1013.4,868.49,46.124756,57.205604,13.357422,210.045455,48.36195,56.431277
25,Spain,32603,1254715,1222112,20827.7,17790.5,797.9,503.5,20029.8,17287.0,60.24261,70.527248,40.86101,64.752731,61.014688,70.695436
26,Sweden,6778.4,485266.9,478488.5,5400.1,5108.8,138.3,42,5261.8,5066.8,89.862577,94.986474,49.012292,161.390476,90.936277,94.436035
27,totEU27,272088.6,14515108.4,14243019.8,214989.23,183819.22,9177.17,3059.83,205812.06,180759.39,67.515514,78.964041,29.648421,88.922783,69.20401,78.795463

In [4]:
eu_productivities = pd.DataFrame()
eu_productivities['country'] = nama_av['country']

eu_productivities['agri tot prod'] = nama_av['agri_tot_prod'] / nama_av.iloc[-1, 12] #  totEU27, 'agri_tot_prod'
eu_productivities['no agri tot prod'] = nama_av['noagri_tot_prod'] /  nama_av.iloc[-1, 14]  # totEU27, 'noagri_tot_prod'

eu_productivities['no agri tot prod Italy-adjusted'] = nama_av['noagri_tot_prod'] /  nama_av.iloc[14, 14] 
eu_productivities

        country agri tot prod no agri tot prod no agri tot prod Italy-adjusted
0       Austria      1.360771         1.262556                        1.224654
1       Belgium       2.13641         1.453364                        1.409733
2      Bulgaria      0.206486         0.362598                        0.351713
3       Croatia       0.81811         0.504158                        0.489023
4        Cyprus       0.74165         0.803747                        0.779618
5       Czechia      1.303595         0.712335                         0.69095
6       Denmark      1.956721         1.547368                        1.500915
7       Estonia      1.741534           0.6914                        0.670644
8       Finland      2.312542         1.225157                        1.188377
9        France      2.159639         1.143633                        1.109301
10      Germany      2.319499         1.139335                        1.105131
11       Greece      0.519914         0.557685                        0.540943
12      Hungary      1.110232         0.433822                        0.420799
13      Ireland      1.977573          2.84821                        2.762706
14        Italy      1.354992          1.03095                             1.0
15       Latvia      0.889279         0.512895                        0.497498
16    Lithuania      1.141507          0.60905                        0.590766
17   Luxembourg      1.405107         2.014101                        1.953636
18        Malta      1.334015         0.833647                         0.80862
19  Netherlands      2.793825         1.285152                        1.246571
20       Poland      0.421423          0.51552                        0.500044
21     Portugal      0.521414          0.61651                        0.598002
22      Romania      0.201762         0.524442                        0.508698
23     Slovakia      1.027641         0.587485                        0.569849
24     Slovenia      0.450527         0.698832                        0.677852
25        Spain      1.378185         0.881664                        0.855196
26       Sweden      1.653116         1.314032                        1.274584
27      totEU27           1.0              1.0                        0.969979

In [5]:
eu_productivities.to_pickle("./eu_productivities.xp")
nama_av.to_pickle("./nama_av.xp")